'use strict';
const assert=require('assert/strict'),M=require('../../main/assets/js/bank-message-core'),I=require('../../main/assets/js/bank-ingestion-core');
const state={institutions:[{id:'b',bankRegistryId:'emirates-nbd',country:'UAE'}],accounts:[{id:'a',type:'bank',institutionId:'b',country:'UAE',currency:'AED'}],paymentInstruments:[{id:'c',type:'debit_card',accountId:'a',institutionId:'b',last4:'4321'}],transactions:[{id:'manual',type:'expense',accountId:'a',currency:'AED',cat:'home',note:'Synthetic Shop',amount:10}],settings:{}};
const p=M.parse({id:'learn',sender:'EmiratesNBD',text:'Purchase AED 12.00 at Synthetic Shop using debit card ending 4321',postedAt:1791288000000});
const route=M.resolveRoute(p,state);I.learnFromApproval(state,p,route,{now:1791288000000,uid:()=> 'rule'});
const before=JSON.stringify(state.transactions);let rows=I.learningEntries(state);assert.equal(rows.length,2);
assert.equal(I.setLearningEnabled(state,'template','rule',false,{now:1791288001000}).ok,true);
assert.equal(I.matchLearnedRule(p,state),null);I.learnFromApproval(state,p,route,{now:1791288002000});assert.equal(I.matchLearnedRule(p,state),null,'ordinary approval must not silently reenable revoked learning');
assert.equal(I.setLearningEnabled(state,'template','rule',true,{now:1791288003000}).ok,true);assert.equal(I.matchLearnedRule(p,state),null,'historical message must not gain new automatic routing');assert.equal(I.matchLearnedRule({...p,postedAt:1791288004000},state).id,'rule');
const merchant=rows.find(x=>x.type==='merchant');assert.equal(I.learnedMerchantCategory(p,state),'home');
I.setLearningEnabled(state,'merchant',merchant.id,false);assert.equal(I.learnedMerchantCategory(p,state),null);
const restart=JSON.parse(JSON.stringify(state));assert.equal(I.learnedMerchantCategory(p,restart),null);I.setLearningEnabled(restart,'merchant',merchant.id,true);assert.equal(I.learnedMerchantCategory(p,restart),'home');
const other={...p,bankId:'emirates-islamic'};assert.equal(I.learnedMerchantCategory(other,state),null,'merchant learning is scoped to the linked account');
const salary=M.parse({id:'salary',sender:'EmiratesNBD',text:'Salary AED 5000.00 credited to your account 012XXX50XXX01',postedAt:1791288000000});
assert.equal(I.confirmAccountIdentity(state,salary,'a',{confirmed:true,now:1791288000000}).ok,true);
rows=I.learningEntries(state);const binding=rows.find(x=>x.type==='identity');assert(binding);I.setLearningEnabled(state,'identity',binding.id,false);
assert.notEqual(M.resolveRoute({...salary,postedAt:1791298000000},state).status,'routed');
const restored=JSON.parse(JSON.stringify(state));I.setLearningEnabled(restored,'identity',binding.id,true,{now:1791288003000});assert.equal(M.resolveRoute({...salary,postedAt:1791298000000},restored).status,'routed');
assert.equal(JSON.stringify(state.transactions),before,'changing future learning does not reinterpret history');assert(state.settings.bankLearningAudit.length>=4);
console.log('Learning controls: scoped merchant/template/identity, revoke/restore, no historical mutation or implicit re-enable');

const custom={institutions:[{id:'custom',name:'Synthetic Institution',country:'UAE',notificationAliases:['QA_SOURCE']}],settings:{}};
const source={sourceHint:'QA_SOURCE',country:'UAE',currency:'AED'};
assert.equal(I.findCustomInstitutionByHint(custom,source).id,'custom');
const alias=I.learningEntries(custom).find(x=>x.type==='source');I.setLearningEnabled(custom,'source',alias.id,false);
assert.equal(I.findCustomInstitutionByHint(JSON.parse(JSON.stringify(custom)),source),null);
I.setLearningEnabled(custom,'source',alias.id,true);assert.equal(I.findCustomInstitutionByHint(custom,source).id,'custom');
