'use strict';
const assert=require('assert/strict');
const M=require('../../main/assets/js/bank-message-core');
const F=require('../../main/assets/js/finance-core');
const R=require('../../main/assets/js/report-core');
const I=require('../../main/assets/js/bank-ingestion-core');
const state={institutions:[{id:'b',bankRegistryId:'emirates-nbd',country:'UAE'}],accounts:[{id:'a',institutionId:'b',type:'bank',country:'UAE',currency:'AED',openingBalance:1000,openingBalanceKnown:true}],paymentInstruments:[{id:'c',accountId:'a',institutionId:'b',type:'debit_card',last4:'4321'}],transactions:[]};
const p=M.parse({id:'synthetic-original',sender:'EmiratesNBD',text:'Purchase EUR 23.45 at Synthetic Store using debit card ending 4321. Transaction reference FXTEST01',postedAt:1791288000000});
const route=M.resolveRoute(p,state);
const pending=M.buildTransaction(p,route,{allowPendingSettlement:true,uid:()=> 'pending-1'});
assert.equal(pending.ok,true,'known purchase can be retained without guessed settlement');
assert.equal(pending.transaction.settlementStatus,'pending');
assert.equal(pending.transaction.walletAmount,null);assert.equal(pending.transaction.fxRate,null);
state.transactions.push(pending.transaction);
assert.equal(F.validateMoneyChanges(state,{...state,transactions:[]}),null);
assert.equal(F.accountMovement(state,'a'),0,'no guessed account movement');
assert.equal(F.accountBalance(state,'a'),null,'incomplete settlement means incomplete balance');
const ds=R.buildReportDataset(state,{country:'UAE',period:'month',month:'2026-10'});
assert.equal(ds.pendingSettlementCount,1);assert.equal(ds.expenses[0].amount,null);assert.equal(ds.expenses[0].originalCurrency,'EUR');
const before=JSON.stringify(state);
const invalid=I.settlePendingPurchase(state,{transactionId:'pending-1',amount:'94.251',fee:'1.25',confirmed:true,now:1791291600000});
assert.equal(invalid.ok,false);assert.equal(JSON.stringify(state),before);
const settled=I.settlePendingPurchase(state,{transactionId:'pending-1',amount:'94.25',fee:'1.25',confirmed:true,now:1791291600000});
assert.equal(settled.ok,true);assert.equal(JSON.stringify(state),before,'settlement proposal is pure until durable commit');
state.transactions[0]=settled.transaction;
assert.equal(state.transactions.length,1);assert.equal(state.transactions[0].id,'pending-1');
assert.equal(state.transactions[0].amount,23.45);assert.equal(state.transactions[0].currency,'EUR');
assert.equal(state.transactions[0].walletAmount,95.5);assert.equal(state.transactions[0].bankPrincipalAmount,94.25);
assert.equal(F.validateMoneyChanges(state,JSON.parse(before)),null);
const tampered=JSON.parse(JSON.stringify(state));tampered.transactions[0].amount=30;
assert.equal(F.validateMoneyChanges(tampered,JSON.parse(before)).reason,'settlement-original-changed');
assert.equal(F.accountBalance(state,'a'),904.5);
assert.equal(R.buildReportDataset(state,{country:'UAE',period:'month',month:'2026-10'}).pendingSettlementCount,0);
assert.equal(I.settlePendingPurchase(state,{transactionId:'pending-1',amount:'94.25',confirmed:true}).ok,false,'replay cannot overwrite confirmed settlement');
assert.equal(M.buildTransaction({...p,kind:'deposit'},route,{allowPendingSettlement:true}).ok,false,'pending flag is not a posting bypass');
console.log('Pending settlement: original preserved, no guessed balance/report, same-event confirmed settlement and exact fees');
for(const [purchaseCurrency,accountCurrency,accountType,instrumentType] of [['MAD','AED','bank','debit_card'],['EUR','AED','bank','debit_card'],['USD','AED','bank','debit_card'],['USD','EGP','credit','credit_card']]){
 const sample=JSON.parse(before);sample.transactions=[];sample.accounts[0].currency=accountCurrency;sample.accounts[0].type=accountType;sample.accounts[0].openingDebt=0;sample.accounts[0].creditLimit=5000;sample.paymentInstruments[0].type=instrumentType;
 const purchase={...p,currency:purchaseCurrency};const built=M.buildTransaction(purchase,{status:'routed',account:sample.accounts[0],instrument:sample.paymentInstruments[0]},{allowPendingSettlement:true,uid:()=> 'currency-case'});
 assert.equal(built.ok,true);sample.transactions=[built.transaction];assert.equal(F.validateMoneyChanges(sample,{...sample,transactions:[]}),null);assert.equal(F.accountMovement(sample,'a'),0);assert.equal(F.accountBalance(sample,'a'),null);
 if(accountType==='credit')assert.deepEqual(R.creditPeriodActivity(sample,'a',{start:'2026-10-01',end:'2026-10-31'}),{purchases:null,pendingSettlementCount:1,repaymentPrincipal:0});
 const proposal=I.settlePendingPurchase(sample,{transactionId:'currency-case',amount:'100',fee:'2',confirmed:true});assert.equal(proposal.ok,true);const original=JSON.parse(JSON.stringify(sample));sample.transactions[0]=proposal.transaction;assert.equal(F.validateMoneyChanges(sample,original),null);assert.equal(sample.transactions[0].currency,purchaseCurrency);assert.equal(sample.transactions[0].walletCurrency,accountCurrency);
 const reverted=JSON.parse(JSON.stringify(original));assert.notEqual(F.validateMoneyChanges(reverted,sample),null,'confirmed settlement cannot silently regress');
}
console.log('MAD/EUR/USD on AED and foreign purchase on EGP credit: pending and confirmed paths');
(async()=>{
 const Mutation=require('../../main/assets/js/mutation-core');
 const clone=v=>JSON.parse(JSON.stringify(v));let live=JSON.parse(before),disk=clone(live),fail=true;
 const service=Mutation.createMutationService({canWrite:()=>true,snapshotState:()=>clone(live),loadState:s=>{live=clone(s);},fingerprint:JSON.stringify,validateChanges:F.validateMoneyChanges,writeSafetySnapshot:async()=>({ok:true}),verifiedWrite:async s=>{if(fail)throw Object.assign(Error('No space'),{name:'QuotaExceededError'});disk=clone(s);return {ok:true};},tryRestore:async s=>{disk=clone(s);return true;}});
 const save=()=>service.run(()=>{const proposal=I.settlePendingPurchase(live,{transactionId:'pending-1',amount:'94.25',fee:'1.25',confirmed:true});assert(proposal.ok);live.transactions[0]=proposal.transaction;return true;});
 assert.equal((await save()).ok,false);assert.equal(JSON.stringify(live),before);assert.equal(JSON.stringify(disk),before,'failed durable save leaves original pending purchase');
 fail=false;assert.equal((await save()).ok,true);assert.equal(live.transactions.length,1);assert.equal(live.transactions[0].bankSettlementAudit.length,1);assert.equal(F.accountBalance(disk,'a'),904.5);
 console.log('Settlement durable-write failure, rollback and retry preserve one event and one audit decision');
})().catch(e=>{console.error(e);process.exitCode=1;});
