'use strict';
const assert=require('assert/strict'),R=require('../../../../tools/quarantine-invalid-asset-income'),S=require('../../main/assets/js/state-core'),B=require('../../main/assets/js/backup-core');
const t={id:'bad',type:'income',accountId:'credit',amount:7200,currency:'AED',walletAmount:7200,created:1000,bankImportKey:'synthetic',bankImportEventId:'synthetic-event',bankId:'emirates-nbd',bankImportEvidence:{kind:'salary',text:'Salary AED 7200 credited to your bank account',sourceHint:'EmiratesNBD',availableBalance:7201}};
const good={id:'refund',type:'income',accountId:'credit',amount:20,currency:'AED',created:2000,bankImportKey:'refund',bankImportEventId:'refund-e',bankImportEvidence:{kind:'refund'}};
const state={schemaVersion:16,institutions:[],accounts:[{id:'credit',type:'credit',country:'UAE',currency:'AED',baselinePartial:true,openingDebt:0,observedBalance:7201,observedBalanceAt:1000},{id:'bank',type:'bank',country:'UAE',currency:'AED',openingBalance:150}],paymentInstruments:[],transactions:[t,good],beneficiaries:[],settings:{bankEventDecisions:{'synthetic-event':{action:'saved',transactionId:'bad'},untouched:{action:'dismissed'}}},categories:{},tags:[],recurring:[]};
const bytes=Buffer.from(JSON.stringify(B.makeFullBackup({state,fingerprint:S.stateFingerprint,features:{bankImportAudit:{smsReviewEvents:[]}},receipts:[]})));
const plan=R.dryRun(bytes);assert.equal(plan.proposals.length,1);assert.equal(plan.proposals[0].id,'bad');
const result=R.apply(bytes,plan),repaired=JSON.parse(result.repaired);
assert.equal(repaired.finance.transactions.length,1);assert.equal(repaired.finance.transactions[0].id,'refund');
assert.equal(repaired.features.bankImportAudit.smsReviewEvents[0].id,'synthetic-event');
assert.equal(repaired.finance.settings.bankEventDecisions['synthetic-event'],undefined);assert.deepEqual(repaired.finance.settings.bankEventDecisions.untouched,{action:'dismissed'});
const I=require('../../main/assets/js/bank-ingestion-core');
assert.equal(repaired.finance.settings.bankReviewHolds?.['synthetic-event']?.reason,'repair-destination-unconfirmed');
assert.equal(repaired.finance.settings.bankReviewHolds['synthetic-event'].quarantinedTransactionId,'bad');
const parsed={recognized:true,eventId:'synthetic-event',bankId:'emirates-nbd',providerId:null,kind:'salary',direction:'credit',amount:7200,currency:'AED',country:'UAE',accountRef:'SYNTHETIC0001',postedAt:1000,confidence:0.99,availableBalance:7350};
assert.equal(I.plan(parsed,repaired.finance).reason,'repair-destination-unconfirmed','a rescan must retain the repair review');
assert.equal(I.plan({...parsed,eventId:'sms-other-channel',postedAt:6000},repaired.finance).reason,'repair-evidence-match-review','another capture channel is a candidate, not an automatic repost');
assert.notEqual(I.plan({...parsed,eventId:'real-different-principal',amount:7250},repaired.finance).reason,'repair-evidence-match-review');
assert.notEqual(I.plan({...parsed,eventId:'real-next-month',postedAt:31*86400000},repaired.finance).reason,'repair-evidence-match-review');
const audit=I.auditWithDurableDecisions({rows:[{id:'synthetic-event',action:'saved'}]},repaired.finance);
assert.equal(audit.rows.find(r=>r.id==='synthetic-event').action,'review','old audit cannot claim the removed posting remains saved');
const restored=JSON.parse(JSON.stringify(repaired.finance));assert.equal(I.plan(parsed,restored).reason,'repair-destination-unconfirmed');
assert.throws(()=>I.rememberEventDecision(restored,'synthetic-event','saved',2000,'new'),/review-confirmation-required/);
I.rememberEventDecision(restored,'synthetic-event','saved',2000,'new',{decisionSource:'user-confirmation'});
assert.equal(restored.settings.bankReviewHolds['synthetic-event'],undefined);
assert.equal(repaired.finance.accounts[1].openingBalance,150);assert.equal(repaired.finance.accounts[0].observedBalance,undefined);
assert.deepEqual(R.rollback(result.repaired,result.journal),bytes);
assert.throws(()=>R.apply(Buffer.concat([bytes,Buffer.from(' ')]),plan),/source-changed/);
assert.throws(()=>R.rollback(Buffer.concat([result.repaired,Buffer.from(' ')]),result.journal),/repaired-copy-changed/);
assert.equal(R.dryRun(result.repaired).proposals.length,0);
const invalidHolds=JSON.parse(bytes);invalidHolds.finance.settings.bankReviewHolds=[];invalidHolds.finance.integrity.fingerprint=S.stateFingerprint(invalidHolds.finance);
const invalidBytes=Buffer.from(JSON.stringify(invalidHolds));assert.throws(()=>R.apply(invalidBytes,R.dryRun(invalidBytes)),/invalid-review-holds/);
const userCorrected=JSON.parse(bytes);userCorrected.finance.transactions[0].userFinancialOverride={source:'user-confirmation'};userCorrected.finance.integrity.fingerprint=S.stateFingerprint(userCorrected.finance);const preserved=R.dryRun(Buffer.from(JSON.stringify(userCorrected)));assert.equal(preserved.proposals.length,0);assert.equal(preserved.unresolved[0].reason,'user-correction-preserved');
console.log('PASS copy-only liability quarantine, review evidence preservation, immutable source and exact rollback');
