'use strict';
const assert=require('assert');
const R=require('../../main/assets/js/uae-bank-registry-core.js');
assert.strictEqual(R.BANKS.length,62);
assert.strictEqual(R.SOURCE.authority,'Central Bank of the UAE (CBUAE)');
assert.strictEqual(R.detect('EmiratesNBD').bank.id,'emirates-nbd');
assert.strictEqual(R.detect('ENBD').bank.id,'emirates-nbd');
assert.strictEqual(R.detect('ADCB transaction alert').bank.id,'adcb');
assert.strictEqual(R.detect('مصرف أبوظبي الإسلامي').bank.id,'adib');
assert.strictEqual(R.detect('Wio Bank').bank.id,'wio');
assert.strictEqual(R.get('ruya').name,'Ruya Community Islamic Bank L.L.C');
assert.strictEqual(Object.keys(R.BANK_LOCALIZATION).length,62);
assert.strictEqual(R.BANKS.every(b=>R.bankDisplayName(b,'ar')&&R.bankShortName(b)),true);
assert.strictEqual(R.getProvider('du-pay').name,'du Pay');
assert.strictEqual(R.detectProvider('Your du Pay wallet').provider.id,'du-pay');
assert.strictEqual(R.getProvider('e-money').legalName,'Digital Financial Services L.L.C.');
assert.strictEqual(R.detectProvider('e& money transfer alert').provider.id,'e-money');
assert.strictEqual(R.detectProvider('Whizmo wallet transfer').provider.id,'whizmo');
assert.strictEqual(R.detectProvider('Pay10 UAE wallet').provider.id,'pay10');
assert.strictEqual(R.detectProvider('FAB Payit Wallet').provider.id,'payit-fab');
assert.strictEqual(R.searchProviders('الأنصاري').some(p=>p.id==='al-ansari-wallet'),true);
assert.strictEqual(R.providerDisplayName('ziina','ar'),'زينة');
assert.strictEqual(R.logoDomain('du-pay'),'dupay.ae');
assert.strictEqual(R.CBUAE_SVF_LICENSEES.length,23);
assert.strictEqual(R.CBUAE_SVF_LICENSEES.every(name=>R.PAYMENT_PROVIDERS.some(p=>p.legalName===name)),true);
assert.strictEqual(R.PAYMENT_PROVIDERS.length,24); // 23 current CBUAE SVF licensees + FAB Payit bank wallet
assert.strictEqual(R.detectProvider('Foris DAX Middle East FZE payment').provider.id,'crypto-com');
assert.strictEqual(R.detectProvider('Taptap Send UAE wallet').provider.id,'taptap-send');
assert.strictEqual(R.detectProvider('Remitly Fintech Services').provider.id,'remitly');
assert.strictEqual(R.detectProvider('Tabby Payments').provider.id,'tabby');
assert.strictEqual(R.logoDomain('ddsc'),'ddsc.ai');
assert.strictEqual(R.search('emirates').some(b=>b.id==='emirates-nbd'),true);
assert.strictEqual(R.search('ابوظبي').some(b=>b.id==='adcb'||b.id==='adib'||b.id==='fab'),true);
assert.strictEqual(R.logoDomain('emirates-nbd'),'emiratesnbd.com');
assert.strictEqual(R.logoDomain('iraqi-islamic-bank'),null);
assert.strictEqual(R.initials('Emirates NBD Bank P.J.S.C'),'EN');
console.log('UAE bank registry regression tests: PASS');
