plugins {
    id 'com.android.application'
}


android {
    namespace 'com.sanad.v9test'
    compileSdk 35

    defaultConfig {
        applicationId 'com.sanad.v9test'
        minSdk 26
        targetSdk 35
        versionCode 90900
        versionName '9.0.9-stability-rc'
    }

    buildTypes {
        debug {
            debuggable true
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    packaging {
        resources {
            excludes += ['/META-INF/{AL2.0,LGPL2.1}']
        }
    }
}

dependencies {
    testImplementation 'junit:junit:4.13.2'
    implementation 'androidx.webkit:webkit:1.14.0'
    implementation 'androidx.core:core:1.15.0'
}

